<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Submit Form</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 flex items-center justify-center min-h-screen">

<?php

if($_SERVER["REQUEST_METHOD"]== "POST"){
    $email = $_POST['email'];
    $Pass1 = $_POST['Pass1'];

    echo ' <div class="absolute top-4 left-4 bg-green-100 text-green-800 border border-green-300 px-4 py-2 rounded-lg shadow">
    email and Pass are submitted
  </div>';


  $server = "localhost";
  $username = "root";
  $Pass = "";
  $database = "filling form";
  
  $conn = mysqli_connect($server, $username, $Pass,$database);

  if (!$conn){
    die("conneection failed :" .mysqli_connect_error());
  }
  echo "Connected successfully <br>";


  $sql = "INSERT INTO `data` ( `email`, `Pass`, `date`) VALUES ( '$email', '$Pass1', current_timestamp()); ";   //remove that id because it automatically generated by the database

  $RESULT = mysqli_query($conn, $sql);

  if($RESULT){
    echo "thanyou for submitting the form <br>";
  }
  else{
    echo "Error creating table: " . mysqli_error($conn);
  }

}



?>

  <form action="/MYFIRSTPHP/storingdata.php" method="POST" class="bg-white p-8 rounded-2xl shadow-md w-full max-w-sm space-y-6">
    <h2 class="text-2xl font-bold text-center text-gray-800">Login</h2>

    <div>
      <label for="email" class="block text-sm font-medium text-gray-700">email</label>
      <input type="email" name="email" id="email" required
             class="mt-1 block w-full rounded-xl border border-gray-300 shadow-sm p-2 focus:ring-blue-500 focus:border-blue-500">
    </div>

    <div>
      <label for="Pass" class="block text-sm font-medium text-gray-700">Pass</label>
      <input type="Pass" name="Pass1" id="Pass" required
             class="mt-1 block w-full rounded-xl border border-gray-300 shadow-sm p-2 focus:ring-blue-500 focus:border-blue-500">
    </div>

    <button type="submit"
            class="w-full bg-blue-600 text-white font-semibold py-2 rounded-xl hover:bg-blue-700 transition">
      Submit
    </button>
  </form>

</body>
</html>
